"""add snapshot_path to version

Revision ID: e689353d069c
Revises: 4109394c1fde
Create Date: 2025-11-19 17:55:43.355953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e689353d069c'
down_revision = '4109394c1fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('version', schema=None) as batch_op:
        batch_op.drop_column('snapshot_path')

    op.drop_table('webhook')
    # ### end Alembic commands ###
