# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from core.selenium.common import initialize_driver


class TestPruebaseleniumtrendingdatasets():
  def setup_method(self, method):
    self.driver = initialize_driver()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pruebaseleniumtrendingdatasets(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(937, 962)
    self.driver.find_element(By.LINK_TEXT, "Download (2.49 KB)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-toggle").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Download (2.21 KB)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-toggle").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("user1@example.com")
    self.driver.find_element(By.ID, "password").send_keys("1234")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(2) .btn:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-toggle").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-group-item:nth-child(2) .btn:nth-child(2) > .feather").click()
    self.driver.find_element(By.CSS_SELECTOR, ".sidebar-toggle").click()
    time.sleep(1)
    self.driver.find_element(By.LINK_TEXT, "Home").click()